baseURL: https://www.amazingdhamma.org/
languageCode: en-us
title: Amazing Dhamma
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: Way to happiness simply...
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/logo.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: PEACE ..
    # Hero subtitle (optional)
    subtitle: Truth sparks liberation, guiding your path to find haven in the moment. Embrace tranquility, exploring the path to inner harmony—one breath at a time.
    # Button text
    buttontext: Let's begin ..
    # Where the main hero button links to
    buttonlink: "/articles/lets-focus-on-happiness/welcome/"
    # Hero image (from static/images/___)
    image: illustrations/worker2.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - stories
    - articles
    - meditation
    - books
    - abhidhamma
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Guidence
    url: /posts/my-first-post/
  #- title: Practices
  #  url: /posts/
  - title: Meditation Centers
    sublinks:
    - title: Naa Uyana
      url: https://nauyana.org/

    - title: Mithirigala
      url: https://www.nissarana.lk/

  - title: Your thoughts
    url: /#yourThoughts

    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /
  # section1:
  #   title: Great power comes
  #   subtitle: with great responsibility
  #   tiles:
  #   - title: App builder
  #     icon: mouse-globe
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Free trial
  #   - title: Cloud integration
  #     icon: laptop-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  #   - title: Add-ons & plugins
  #     icon: plug-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  section2:
    title: Latest on the site
    subtitle: Food for thought
    
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: logo.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: false
    quicklinks:
      column1:
        title: "About"
        links:
        - text: About Us
          link: /
        - text: Contacts
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
